//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace outflagsUI.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("outflagsUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {
        /// &quot;outFlags1&quot;: [
        ///  {
        ///   &quot;name&quot;: &quot;PF_OutFlag_KEEP_RESOURCE_OPEN&quot;,
        ///   &quot;value&quot;: 1,
        ///   &quot;bit&quot;: 0,
        ///   &quot;description&quot;: &quot;AE 2015で廃止（設定しても何もしない）。グローバルセットアップ以外の時にMacintoshリソースフォークを開いておくことをエフェクトが期待する場合、このフラグを設定します。リソースフォークが常に開いているという意味ではなく、エフェクトが実行されている間だけ開いているという意味です。&quot;,
        ///   &quot;relevant_commands&quot;: &quot;PF_Cmd_GLOBAL_SETUP&quot;
        ///  },
        ///  {
        ///   &quot;name&quot;: &quot;PF_OutFlag_WIDE_TIME_INPUT&quot;,
        ///   &quot;value&quot;: 2,
        ///   &quot;bit&quot;: 1,
        ///   &quot;description&quot;: &quot;エフェクトが現在時刻以外の時刻でパラメータを問い合わせるためにget_paramを呼び出す場合（例：前のビデオフレームを取得する）、このフラグを設定します。送信する場合はPF_Cmd_GLO [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OutflagsList {
            get {
                return ResourceManager.GetString("OutflagsList", resourceCulture);
            }
        }
    }
}
